Repository bepolytech/ULBDiscordBot, pull requests merged in 2024-04, with the labels that each got.

#37 Update Python to 3.11.6 and upgrade dependencies
  Dockerfile
  requirements.txt
Labels: dependencies, Medium Priority

#44 fix #36 : rename user choice during update_all_guilds for admins' `/update`
  classes/utils.py
  cogs/Admin.py
Labels: enhancement, High Priority

#43 fix #42 : filter names to remove unwanted characters
  classes/registration.py
Labels: bug, High Priority

#24 update to disnake 2.9 and python 3.11 compatibility
  Dockerfile
  requirements.txt
Labels: dependencies, Medium Priority
